name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag withnoword/gamepad:$(date +%s)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Push
      - uses: opspresso/action-docker@v0.2.2
        with:
            registry-type: --docker# optional, default is --docker
