name: Docker Image CI

on: #[push, pull_request]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag ${USERNAME}/gamepad:$(date +%s) && echo "username=${USERNAME}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Build & Push to Docker Hub
    - uses: opspresso/action-docker@v0.2.2
      with:
        registry-type: --docker# optional, default is --docker
