name: Docker Image CI

on: #[push, pull_request]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          fetch-depth: 1
      # run: docker build . --file Dockerfile --tag ${USERNAME}/gamepad:$(date +%s) && echo "username=${USERNAME}"

    - name: Build & Push to Docker Hub
      uses: opspresso/action-docker@v0.2.2
      with:
        registry-type: --docker # optional, default is --docker
      env:
        IMAGE_NAME: gamepad
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        TAG_NAME: ${{ $(date +%Y%m%d_%H%M%S) }}
        LATEST: "true"
